### ISSUE TITLE
Version numbering mismatch/issue

### ISSUE THREAD

**Issue by vibonacci** [niiknow/vue-datatables-net#12]
Small issue, but I see v0.1.4 in my package.json file, while the npm website shows 1.1.4

**Comment by noogen** [comment]
There has never been a version v0.1.4 so how are you getting that?  My package.json look like so:
```
"vue-datatables-net": "^1.1.4",
```

**Comment by vibonacci** [comment]
got the wrong package, vue-datatables, whoops
