### ISSUE TITLE
Individual column searching

### ISSUE THREAD

**Issue by atiar-cse** [niiknow/vue-datatables-net#15]
Hi,

Is there a way for - multi column searching like https://datatables.net/examples/api/multi_filter.html ?

Thanks & Regards!

**Comment by noogen** [comment]
The currently implementable simply does server-side search for the value on all searchable fields.  I have not done anything to make individual field filtering easier but you can definitely do it with datatables.net native way.  Feel free to do a pull request if you want to make improvement on this plugin.  

But based on the instruction you link, it's simply:

1.  On initComplete, render the filter fields on footer or header of the table for each column.
2.  Search field can either be filter by client-side or server-side by passing in query string for individual column as in, fname=blah&email=blah@blah.  More details example on server-side searching with laravel datatables.net implementation: https://itsolutionstuff.com/post/custom-filter-search-with-laravel-datatables-exampleexample.html

```javascript
        ajax: {
          url: ...,
          data: function (d) {
                d.email = $('.searchEmail').val(),
                d.fname = $('input[name="fname"]').val()
            }
        }
```

**Comment by dct24** [comment]
How to render the filter fields on header of the table for each column on initComplete or on table-created event?
