### ISSUE TITLE
Hardcoded .table-responsive class results in permanently visible horizontal scrollbars

### ISSUE THREAD

**Issue by omnichronous** [niiknow/vue-datatables-net#16]
Bootstrap provides resolution-specific variants of this class to work around this issue, such as `table-responsive-xl`. It would be better if the user could set their own class on the table wrapper instead of having to manually do it with jQuery after table initialization.

**Comment by noogen** [comment]
You can now configure it - https://github.com/niiknow/vue-datatables-net/blob/62831b8a2a118605606c9b1cbc7f3fbe4446a185/src/VdtnetTable.vue#L53
