### ISSUE TITLE
Handle search, page and order events

### ISSUE THREAD

**Issue by jonathanoh1** [niiknow/vue-datatables-net#17]
I want to execute methods in vue, but i do not find the event dispatched when 'search', 'pagination', and 'order' are used.
According [datatable events](https://datatables.net/examples/advanced_init/dt_events.html), these events exists using instance of datatable, i need detect it when event is fired and execute code but from Vue.

**Comment by jonathanoh1** [comment]
Yes, now I just need to find out how to display the list buttons if the user has permissions or not.

Another question, using `defaultContent`, in the` data-action` attribute, can I use any action ('edit,' 'delete', ...,  'other') and use it as (@edit, @delete, ..., @other)?

**Comment by jonathanoh1** [comment]
But using defaultContent, how can I verify  if the user has permission to `edit`, `delete`, etc, to show the action button?

Another question, using defaultContent, in the data-action attribute, can I use any action ('edit,' 'delete', ..., 'other') and use it as (@edit, @delete, ..., @other)?

**Comment by noogen** [comment]
@jonathanoh1  - sorry for late response, long Holiday weekend.  Anyway, since I provide 3 different methods of templating, instead of `defaultContent`, you can also use `render` function or `template` property to do this.  I've also added `vdtnet` context in the latest version `1.2.0` to help make it easier.  Let assume you have a global mix-in that provide a `can` function for permission checking.

You can use the `render` function instead of `defaultContent`
```js
const vm = this

// ... some code here ...

actions: {
  label: 'Actions',
  render: () => {

     let result = '<a href="javascript:void(0);" data-action="showdropdown" class="btn btn-primary btn-sm"><i class="mdi mdi-menu"></i> ... </a>';

     if (vm.can('write')) {
       result += '<div class="dropdown hidden"><button data-action="edit">one</button>';
     }

     // since 1.2.0, this or this.vdtnet is the same as vm in this example
     // you get the idea
     return result;
}

// ... some code here ...
```

Or use the `template` property instead of defaultContent:
```js
actions: {
  label: 'Actions',
  template: '
<a href="javascript:void(0);" data-action="showdropdown" class="btn btn-primary btn-sm"><i class="mdi mdi-menu"></i> ... </a><div class="dropdown hidden" v-if="vdtnet.can('write')"><button data-action="edit">one</button><button data-action="delete" vdtnet.can('delete')>two</button></div>
'
```

**Comment by noogen** [comment]
@jonathanoh1 I added native templating in 1.2.2, which should help - https://github.com/niiknow/vue-datatables-net#native-templating-sort-of-explained
