### ISSUE TITLE
Data Table inside Details on collapsable button click

### ISSUE THREAD

**Issue by mavrickp** [niiknow/vue-datatables-net#18]
Need Data Table inside Details on collapsible button click

**Comment by noogen** [comment]
@mavrickp You can now template with details row: https://github.com/niiknow/vue-datatables-net/blob/master/example/app.vue#L62 - hopefully, this will help with what you are doing.

Though, if your data on the child/details DataTable is *not* static but dynamic, I would suggest you render your own table, a modal, or even separate page.

**Comment by noogen** [comment]
Old issue with no updates.
