### ISSUE TITLE
How can we add/append column fields in mounted()

### ISSUE THREAD

**Issue by gwachhamit** [niiknow/vue-datatables-net#21]
How can we add/append column fields in mounted()
I want to add extra column fields in table, but the columns are dynamic, passed from backend.

I have added like this in beforeTableCreating event
```
doSomethingBeforeDataTableCreate(){
            this.fields.test = { label: 'Test', sortable: true, searchable: true ,className:"textg" };
        },
```
but it is not working

**Comment by noogen** [comment]
You can't.  You have to do it before the mounted event.  At 'table-creating' event, fields are already created into datatable.net representation of columns.   

This mean that you must have fields schema before creation of the component.  If you want to retrieve fields schema from some ajax call, then what you could do is to use `v-if` before creating the table.   Something like this.

```
<template>
... omitted ...
<div v-if="fields">
   <vdtnet-table
      ref="table"
      :fields="fields"
      :opts="options"
   />
</div>
... omitted ...
<script>
... omitted ...
const that = this
ajaxForFields.then((rsp) => {
   that.fields = rsp.data
})
... omitted ...
</script>
```

**Comment by gwachhamit** [comment]
> You can't. You have to do it before this component mounted event. At `table-creating` event, fields are already created into datatable.net representation of columns.
> 
> This mean that you must have fields schema before creation of the component. If you want to retrieve fields schema from some ajax call, then you can try `v-if` before creating the table. Something like this.
> 
> ```js
> <template>
> ... omitted ...
> <div v-if="fields">
>    <vdtnet-table
>       ref="table"
>       :fields="fields"
>       :opts="options"
>    />
> </div>
> ... omitted ...
> </template>
> <script>
> ... omitted ...
> data() {
>   return { 
>     options: { ... omitted ... },
>     fields: null 
>   }
> }
> .. omitted
> const that = this
> ajaxForFields.then((rsp) => {
>    that.fields = rsp.data
> })
> ... omitted ...
> </script>
> ```
> 
> ===
> Alternatively, if you know there are a specific number of additional field and/or that the field is calculate/computed, you can define the field as `isLocal` property to true and just template it from the server data.

what do you mean by ajaxForFields.then.. in
```
const that = this
ajaxForFields.then((rsp) => {
   that.fields = rsp.data
})
```
I got confused.

**Comment by gwachhamit** [comment]
i do not get it, the section of omitted as you referenced.
when should i call this?
```
ajaxForFields.then((rsp) => {
   that.fields = rsp.data
})
```

Here, I tried the fields axios request in created() and mounted() hook. And the following errors shows.
`[Vue warn]: Error in mounted hook: "TypeError: n.DataTable is not a function"`

**Comment by noogen** [comment]
You can call that whenever.  As long as you do assign fields with something, because once fields is assigned, that's when the component get created with the `v-if`

**Comment by gwachhamit** [comment]
I dont know why, But in my case event setting a time out is not working. It still says
`[Vue warn]: Error in mounted hook: "TypeError: n.DataTable is not a function"`

in mounted(), if i directly assign predefined fields, it works fine. And If i use setTimeout() for those then, it shows the above error.

**Comment by noogen** [comment]
That error means it doesn't have the right jQuery at the time of `mounted` event because DataTable function doesn't exist on that jQuery.  I think you have a race condition with jQuery (multiple loaded) somewhere:  Meaning that a later jQuery get loaded and it overridden the old jQuery that has the DataTable.   This is a common problem that can lead to other issue in your code.

I allow for passing in a jquery instance to my component - https://github.com/niiknow/vue-datatables-net/blob/master/src/VdtnetTable.vue#L89

Simply save the correct jQuery and pass it into the component.

```javascript
import $ from 'jquery'

export default {
... omitted ...
  data() {
    return {
... omitted ...
      jq: $
... omitted ...
   }
... omitted ...
```
```html
... omitted ...
    <vdtnet-table
       :jquery="jq"
... omitted ...
    />
... omitted ...
```

**Comment by gwachhamit** [comment]
@noogen Thank you very much. The problem was multiple loading of jquery. It works now. Once again, Thank you.

**Comment by noogen** [comment]
@gwachhamit no problem, it's a common issue that's why I spotted right away and have a specific property on the component with the description as `Pass in DataTables.Net jQuery to resolve any conflict from multiple jQuery loaded in the browser`
