### ISSUE TITLE
How to trigger an event when data in datable changes?

### ISSUE THREAD

**Issue by gwachhamit** [niiknow/vue-datatables-net#22]
I particularly want to trigger an event when data changes when we search in search box.
The reloaded event is not working in my case.
`@reloaded="doSomethingWhenReloaded"`
When will be the event, `reloaded`  got triggered?

**Comment by noogen** [comment]
`reloaded` is used to detect when data returned from ajax.

Since this is simply a wrapper, you can use `@table-created="doSomethingImmediatelyAfterTableCreatedAndInitialized"` to wire into native datatables.net event.

```javascript
 doSomethingImmediatelyAfterTableCreatedAndInitialized(vdtnet) {
    // use vdtnet.dataTable to access the jQuery DataTables object
    vdtnet.dataTable.on( 'search',  function () { 
        // do something here
    });
});
```

**Comment by gwachhamit** [comment]
Thank you for the reply. It worked for me.
