### ISSUE TITLE
Browser version 

### ISSUE THREAD

**Issue by Herz3h** [niiknow/vue-datatables-net#24]
Hello,

I'm trying to use this dataTables wrapper in a legacy webproject, that does not use npm, but imports js files with script tags (either from local or from cdn). So is there a version I can simply drop in a <script> tag and that would work ? 

I already have vue 2 and dataTables included.

Thanks in advance.

**Comment by noogen** [comment]
All/most npm packages are automatically provided by unpkg cdn.  For latest version of any npm package, simply use https://unpkg.com/packagename or `https://unpkg.com/vue-datatables-net`

**Comment by Herz3h** [comment]
Ok will try, ty
