### ISSUE TITLE
Loading local data

### ISSUE THREAD

**Issue by pututbawono** [niiknow/vue-datatables-net#28]
Is it possible to use this wrapper to load local data, namely data from a v-model ?
I want to display the selected options from a multiselect element in a table. I know it can be done using standard bootstrap table, but I need the ease of DataTables features like search, pagination, filter, etc.
I see this wrapper has a prop that I think can be used (the dataLoader parameter), but it's said it hasn't been tested.
Please help, thanks.

**Comment by ejohmac** [comment]
I'm looking for something similar - simple client-side loading of data into the data tables component through a prop? I've looked through the docs and examples but they all seem to mention server-side processing.

Many thanks

**Comment by noogen** [comment]
Old documentation as it wasn't originally planned, but I've used it in several projects and it works fine.  The logic is a callback function that return array of data.  You simply bind a function that call the callback method to return array of items.   Example:

```html
:data-loader="yourFunction"

methods:{
  yourFunction(callback) {
     const that = this
     const itemsArray = that.model.children
     callback(itemsArray)
  }
}
```

**Comment by pututbawono** [comment]
@noogen,
So for example, if my v-model parameter is `myChoices` (which is already an array) and I've already defined it in the `data()` methode of my component, all I have to do is `callback(this.myChoices)`?
Do I have to define `callback` itself?

**Comment by noogen** [comment]
The component expect that you pass in a method that accept 1 parameter that is a function.  So the answer is yes, callback is whatever you call as first parameter of the dataLoader method.    Let say your dataLoader method is called `someMethod()`, then you would define it like so:

```
someMethod(cb) {
  // since you already define myChoices in data(), simply return it here
  cb(this.myChoices)
}
```

**Comment by pututbawono** [comment]
@noogen, I got an error. This is the dataLoader part I put in the wrapper options :
```
dataLoader: {
    tableData() {
        cb(this.groupAlat);
    }
},

```
`this.groupAlat` is a v-model from a multiselect box, defined as `groupAlat: []` in the return part of `data()` method.
When I look at the reponse of datatable, it was the HTML of the page, not a JSON at all. 
So, where am I doing wrong?

**Comment by pututbawono** [comment]
@noogen, nevermind....silly of me, I still use `serverSide: true` in my options :smile:.
Thanks for the help!

**Comment by pututbawono** [comment]
So after a lof of mix-ups, here's what I got in my code : 
```
// in <vdtnet-table> tag :
:dataLoader="loaderGroupAlat"

// in method() part of the Vue : 
loaderGroup (cb) {
    cb(this.groupAlat)
}
```
`this.groupAlat` is a v-model parameter from multiselect box and it's an array of objects, defined in the `return {}` part `data()` as `groupAlat: []`.
This doesn't work, and I got an error message `Error in mounted hook: "TypeError: Cannot read property 'style' of undefined"`.
What did I do wrong?

**Comment by noogen** [comment]
It should be.  
```html
:data-loader="loaderGroupAlat"
```

Also, that error is something else.  You have some bad html somewhere relating to a component that has "style" attribute definition.

**Comment by pututbawono** [comment]
I've used vdtnet-table on usual server-side scripting and using camelCase, but there's no error regarding that. 
If I remove the `:data-loader` prop from the vdtnet tag, the error message is gone. 
I'm sure I don't use style attribute anywhere on the page.
Also, on mounted phase, there's nothing showing on the table even though `this.groupAlat` has values in it. But when I change the selection in multiselect element, the table shows the data. I think it has something to do with the error message I mentioned before.

**Comment by ejohmac** [comment]
Thanks @noogen I'll check out that table.
Appreciate the reply

**Comment by noogen** [comment]
Stale issue.
