### ISSUE TITLE
Creating radio button on each row

### ISSUE THREAD

**Issue by pututbawono** [niiknow/vue-datatables-net#30]
So I need to create radio button on each of the row, so user can select the radio button to indicate their choice. Why I need radio button? Because the user is only allowed to choose 1 of the rows.
I think I almost got this, but the problem is the radio button from previously selected row wouldn't turn off as expected in "normal" radio button.
I'm using native template for this purpose, and this is how I do it :

- In the `fields` definition :
```
choose : {label : 'Choose', data: 'chosenData'}
```

- In the `template` : 
```
<template slot="choose" slot-scope="ctx">
   <input type="radio" class="form-control" :id="ctx.data.id" :value="ctx.data.value" v-model="chosen">
</template>
```

Please help, thanks.

**Comment by noogen** [comment]
Stale issue.
