### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by bernietai** [niiknow/vue-datatables-net#32]
On https://niiknow.github.io/vue-datatables-net/ , attempting to sort fields such as "ID", "Name", "Email" does not work. See screenshot 

<img width="1276" alt="Screen Shot 2020-03-14 at 1 01 23 pm" src="https://user-images.githubusercontent.com/10083575/76686732-f9c33680-65f3-11ea-8762-f76b3187a04b.png">

**Comment by noogen** [comment]
Yes, because I'm really not using the right back-end that support datatables.net server-side.   As a result, paging does not work either.  I will have to switch to a different back-end and update the doc.

**Comment by thetuyo** [comment]
Can anyone confirm the example shown on the home page actually works simply using NPM to install the libs and importing all the libs as shown.  I'm not even able to instantiate.

<img width="743" alt="image" src="https://user-images.githubusercontent.com/9757103/81076549-c39a8880-8eb9-11ea-8f42-60eb84e33452.png">

**Comment by wilsonwg** [comment]
Hello, I just tried out the demo, but I always get the error message:

![Screenshot_2020-06-03_20-06-05](https://user-images.githubusercontent.com/10696151/83635442-cf6f8c80-a5d6-11ea-822e-de98e02b3010.png)

These are my steps:
git clone https://github.com/niiknow/vue-datatables-net
cd vue-datatables-net
npm install
npm run watch

No files were edited. I unlocked CORS with an extension.

**Comment by noogen** [comment]
Stale issue.
