### ISSUE TITLE
Change Select type to multi

### ISSUE THREAD

**Issue by torriv83** [niiknow/vue-datatables-net#33]
hi, 

i'm trying to change the select type to multi, but it doesn't seem like will change. it's still 'os'. 

i've tried to set this under options:
 ```
select: {
          style: 'multi'
        }
``` 

any suggestions? :)

**Comment by noogen** [comment]
This is fixed.  Don't know why I did a jquery extend instead of just stop there.  There was probably a confusion at that point in the code with the select-checkbox implementation.

**Comment by torriv83** [comment]
Awesome! can confirm it works now :) 

just a side quiestion: is it possible to style the checkboxes? usually we have to do something like this:

` <label><input type="checkbox" name="foo" value="bar">
                                            <span></span>
</label>`

And then style it in css.

**Comment by torriv83** [comment]
AND +1 for this todo ;) 

https://github.com/niiknow/vue-datatables-net/blob/f014858abce738c937f1ed4b79453544b6e70696/src/VdtnetTable.vue#L357

**Comment by noogen** [comment]
Done

**Comment by torriv83** [comment]
Thank you for really fast and good support! 

i managed to style the checkboxes almost 100% the way i wanted! :) 
![checkboxes_25 03 2020_13 57 37](https://user-images.githubusercontent.com/15953693/77547533-9bc50780-6ead-11ea-9733-85aeb29000e5.png)

When it comes to the $emit:

i was thinking to toggle a actionbar on and off. so, if you click one or several checkboxes, a toolbar with "delete selected rows", or "edit selected row" would show up. In that way, i don't need to have those buttons visible at first, hence save space on smaller screens and make it more clean.  

but i'm not sure if it works the way i want. 
would be nice if the $emit would have all the checked boxes with their id's in it, so i could just send those values to the backend and delete. 

Anyway, thank you for your help!

**Comment by noogen** [comment]
@torriv83 Did you see my comment in the file?  https://github.com/niiknow/vue-datatables-net/blob/8b50c83ee80ea990caf1d3ff226cf9476042c593/src/VdtnetTable.vue#L368

It's easy, here's sample code:
```js
...omitted...
@row-select="handleRowSelect"
...omitted...
<script>
...omitted...
handleRowSelect(event) {
  // let say you want to get all rows that were just selected
  const rows = event.dataTable.rows( event.indexes )
  const items = rows.data()

  // and let say you want to get all id properties
  const ids = []
  items.forEach((v) => {
    ids.push(v.id)
  })
  // so you see, handling deselect and get all newly deselected row is the same

  // or if you want to simply get all selected rows
  const allSelectedRows = event.dataTable.rows({ selected: true })
  const allNotSelectedRows = event.dataTable.rows({ selected: false })
}
...omitted...
</script>
```

**Comment by torriv83** [comment]
thanks for your example. 

just tried out your code, and i got: 
Error in v-on handler: "TypeError: items.forEach is not a function"

a console.log on items gives: 

`
_Api [{…}, context: Array(1), selector: {…}, tables: ƒ, table: ƒ, draw: ƒ, …]
0:
    id: (...)
    fra_dato: (...)
    til_dato: (...)
    description: (...)
    totalt: (...)
    user_id: (...)
    unavailable: (...)
    allDay: (...)
    created_at: (...)
    updated_at: (...)
    deleted_at: (...)
    user: (...)
__ob__: Observer {value: {…}, dep: Dep, vmCount: 0}
--- omitted...`

**Comment by noogen** [comment]
Sorry, I thought `.data()` return an array which I was wrong.  It's a wrapper object so I think you have to use regular for loop instead of shortcut forEach of Array prototype: `for(let i=0; i<items.length; i++) { const item = items[i] ... }`

**Comment by torriv83** [comment]
i got it working now :) 

just need to figure out where to put them buttons! ;) is there a way to add a extra row on the top of the table that is visible when the count of the array is > 1?, and make that row stick? 

btw, i'm not sure if it's my bad programming or a bug, but these issues has come up: 

scenario 1:
i click on "check all", then deselect one row. the "check all" is still checked. 

scenario 2: 
i click on 3 of the rows, then click "check all". it doesn't remove those 3 and then add them all. but add everyone plus those 3 ... so, if my array has 5 items, i click 3, then check all, the array then has 8 items in it. not 5.

some code:

```
rowSelect(event){

        const rows  = event.dataTable.rows( event.indexes )
        const items = rows.data()
 
        for(let i=0; i<items.length; i++) { 
             this.selected.push(items[i])
            }

        // const allSelectedRows    = event.dataTable.rows({ selected: true })
        // const allNotSelectedRows = event.dataTable.rows({ selected: false })

    },


    rowDeselect(event){

        const rows  = event.dataTable.rows( event.indexes )
        const items = rows.data() 
        
        for(let i=0; i<items.length; i++){
            
            const index = this.selected.indexOf(items[i]);

            this.selected.splice(index, 1);

        }
```

**Comment by noogen** [comment]
@torriv83 - I think you ran into the issue that I ran into when using select `multi` instead of default `os` option.    That's probably why I force the default select `os` option.  Can you try with default and not select `multi` option to see if you're still having that issue?   User can always multiple select by doing shift or ctrl/command click of checkbox.   

As for buttons, I suggest not using the built-in buttons and render them yourself?  Example:  https://laratt.niiknow.org/home/contacts and the code https://github.com/niiknow/laratt-api/blob/master/resources/js/components/DataTableNet.vue

**Comment by torriv83** [comment]
none of the scenarios was fixed with having the select to "os". 

and for buttons: yes, i was going to use my "own" buttons, since i'm using a template, i will use that templates button. 

i'll look more into the button part tomorrow. :)

**Comment by torriv83** [comment]
okey, i'm back. had some issues with my development environment and had to change it. 

anyways, i just made a solution for scenario 2 (described earlier).

this is the code that fixed it: 

```
if (event.dataTable.page.info().recordsTotal == items.length) {
    this.selected = [];
}

for (let i = 0; i < items.length; i++) {
    this.selected.push(items[i]);
}
``` 

haven't found any solutions for scenario 1 yet..

**Comment by torriv83** [comment]
I fixed it!

Solution on rowDeselect:

```
//Deselect "select all" Checkbox
var elements = document.getElementsByClassName(
    "select-all-checkbox"
);

for (var inp of elements) {
    if (inp.type === "checkbox") inp.checked = false;
}
```

**Comment by noogen** [comment]
Stale issue.
