### ISSUE TITLE
TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by joweste** [niiknow/vue-datatables-net#34]
Hi, I am trying to use this component,

I am getting the next error:. What am I doing wrong?
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'extend' of undefined"

found in

---> Vue warn]: Error in created hook: "TypeError: Cannot read property 'extend' of undefined"

found in

---> <VdtnetTable> at src/components/VdtnetTable.vue
       <TesteVDNetTableComponent> at src/components/TesteVDNetTableComponent.vue
         <HelloWorld> at src/components/HelloWorld.vue
           <App> at src/App.vue
             <Root>
```

I just copied from example and I created  this TesteVDNetTableComponent.vue:


```
```
<template>
  <div class="col-12">
    <div class="row">
      <div class="col-12 col-md-9">
        Below are client-side buttons demo, go here to see
        <a
          href="https://laratt.niiknow.org/home/contacts"
          target="_blank"
        >server-side buttons demo</a>
      </div>
      <div class="col-12 col-md-3">
        <form class="form-inline d-flex mx-1 justify-content-end" @submit.stop.prevent="doSearch">
          <div class="input-group">
            <input
              v-model="quickSearch"
              type="search"
              placeholder="Quick search"
              class="form-control"
            />
            <div class="input-group-append">
              <button type="submit" class="btn btn-outline-secondary">
                <i class="mdi mdi-magnify" /> Go
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- Using the VdtnetTable component -->
    <vdtnet-table
      ref="table"
      :fields="fields"
      :opts="options"
      :select-checkbox="1"
      :details="details"
      @edit="doAlertEdit"
      @delete="doAlertDelete"
      @reloaded="doAfterReload"
      @table-creating="doCreating"
      @table-created="doCreated"
    >
      <template slot="HEAD__details_control">
        <b>Show Details</b>
      </template>
      <template slot="address2" slot-scope="ctx">
        <span>
          {{ ctx.data.city }},
          {{ ctx.comp.formatCode(ctx.data.zipcode) }}
        </span>
      </template>
      <template slot="_details" slot-scope="ctx">
        <strong>I'm a child for {{ ctx.data.id }} yall</strong>
      </template>
    </vdtnet-table>
  </div>
</template>

<script>
// this demonstrate with buttons and responsive master/details row
import VdtnetTable from "./VdtnetTable";
import "datatables.net-bs4";
// import buttons and plugins
import "datatables.net-buttons/js/dataTables.buttons.js";
import "datatables.net-buttons/js/buttons.html5.js";
import "datatables.net-buttons/js/buttons.print.js";
// import the rest
import "datatables.net-buttons-bs4";
import "datatables.net-select-bs4";
import "datatables.net-select-bs4/css/select.bootstrap4.min.css";
import "datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css";
export default {
  name: "TesteVDNetTableComponent",
  components: { VdtnetTable },
  data() {
    const vm = this;
    return {
      options: {
        ajax: {
          url: "https://jsonplaceholder.typicode.com/users",
          dataSrc: json => {
            console.log(json);
            return json;
          }
        },
        buttons: ["copy", "csv", "print"],
        /*eslint-disable */
        dom:
          "Btr<'row vdtnet-footer'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'pl>>",
        /*eslint-enable */
        responsive: false,
        processing: true,
        searching: true,
        searchDelay: 1500,
        destroy: true,
        ordering: true,
        lengthChange: true,
        serverSide: true,
        fixedHeader: true,
        saveState: true /*,
        select: {
          style: 'multi'
        }*/
      },
      fields: {
        id: { label: "ID", sortable: true },
        actions: {
          isLocal: true,
          label: "Actions",
          defaultContent:
            '<a href="javascript:void(0);" data-action="edit" class="btn btn-primary btn-sm"><i class="mdi mdi-square-edit-outline"></i> Edit</a>' +
            '<span data-action="delete" class="btn btn-danger btn-sm"><i class="mdi mdi-delete"></i> Delete</span>'
        },
        name: {
          label: "Name",
          sortable: true,
          searchable: true,
          defaultOrder: "desc"
        },
        username: { label: "Username", sortable: false, searchable: true },
        email: { label: "Email" },
        address1: {
          label: "Address1",
          data: "address",
          template: "{{ data.street }}, {{ data.suite }}"
        },
        address2: {
          label: "Address2",
          data: "address"
        },
        phone: { label: "Phone" },
        website: {
          label: "Website",
          render: data => {
            return `https://${data}`;
          }
        }
      },
      quickSearch: "",
      details: {}
    };
  },
  methods: {
    doLoadTable(cb) {
      $.getJSON("https://jsonplaceholder.typicode.com/users", function(data) {
        cb(data);
      });
    },
    doAlertEdit(data) {
      window.alert(`row edit click for item ID: ${data.id}`);
    },
    doAlertDelete(data, row, tr, target) {
      window.alert(`deleting item ID: ${data.id}`);
      // row.remove() doesn't work when serverside is enabled
      // so we fake it with dom remove
      tr.remove();
      const table = this.$refs.table;
      setTimeout(() => {
        // simulate extra long running ajax
        table.reload();
      }, 1500);
    },
    doAfterReload(data, table) {
      window.alert("data reloaded");
    },
    doCreating(comp, el) {
      console.log("creating");
    },
    doCreated(comp) {
      console.log("created");
    },
    doSearch() {
      this.$refs.table.search(this.quickSearch);
    },
    doExport(type) {
      const parms = this.$refs.table.getServerParams();
      parms.export = type;
      window.alert("GET /api/v1/export?" + jQuery.param(parms));
    },
    formatCode(zipcode) {
      return zipcode.split("-")[0];
    }
  }
};
</script>

<style scoped></style>

```
```

**Comment by noogen** [comment]
Do you have jQuery loaded?  Make sure that it is loaded before everything else.  datatables.net depends on jQuery.

**Comment by joweste** [comment]
Hi, Yes I am jQuery Loaded.
Here is my Main.js

import Vue from "vue";
import App from "./App";
import router from "./router";

import "bootstrap/dist/css/bootstrap.min.css";
import $ from "jquery";

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: "#app",
  router,
  render: h => h(App)
});

**Comment by joweste** [comment]
I changed my Main.js to next I now I get a different error: "vue.complie is not a function".
I seraqch on google nad I found:
import Vue from 'vue'imports the runtime-only build, which does not have the compiler.

But, you are using "compile function".
Can you fix it?


```
import Vue from "vue";
import App from "./App";
import router from "./router";

import jQuery from "jquery";

import "bootstrap/dist/css/bootstrap.min.css";

window.Vue = Vue;
window.jQuery = jQuery;

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: "#app",
  router,
  render: h => h(App)
});

```

Vue warn]: Error in mounted hook: "TypeError: vue.compile is not a function"

found in

---> <VdtnetTable> at src/components/VdtnetTable.vue
       <TesteVDNetTableComponent> at src/components/TesteVDNetTableComponent.vue
         <HelloWorld> at src/components/HelloWorld.vue
           <App> at src/App.vue
             <Root>

**Comment by noogen** [comment]
Since you're not loading jQuery globally (reference as script object on the page before everything else), you can load it into my component `jquery` property like so https://github.com/niiknow/vue-datatables-net/issues/21#issuecomment-572129857

I suggest that you load jGuery globally.  Otherwise, instead of the `import "datatables.net-bs4"`, you will have to load datatables.net-bs4 like so:
```
var $ = require( 'jquery' );
// this is how you pass in jquery to datatables.net if you didn't load it globally
require( 'datatables.net-bs4' )( $ );
```

ref: https://www.npmjs.com/package/datatables.net-bs4

**Comment by joweste** [comment]
Please, How about the compile problem?

**Comment by noogen** [comment]
Same answer, my component also have a `vue` property.  Either load it globally or pass it into my component like the jquery example.

**Comment by joweste** [comment]
But the default import of the Vue has no compile function. 
See at:  https://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build

**Comment by noogen** [comment]
`https://vuejs.org/v2/api/#Vue-compile` yes it does.  It's part of Vue and is how I use it to support native templating (sort-of).

**Comment by joweste** [comment]
I put a console.log(vue) before the next line of VdtnetTable:
console.log(vue);
const res = vue.compile(<div>${field.template || ""}</div>);

This is the result. So vue is ok, but compile is not found. I am  stuck here.

vue: ƒ Vue (options) {
  if ("development" !== 'production' &&
    !(this instanceof Vue)
  ) {
    warn('Vue is a constructor and should be called with the `new` keyword');
  }
  this._init(options);
}

**Comment by joweste** [comment]
I am using vue webpack template from https://github.com/vuejs-templates/webpack

**Comment by joweste** [comment]
I am trying to find how Install the full build of the view  to test it now.

**Comment by noogen** [comment]
Either reference vue gobally or pass in vue as a component property like example of jQuery here https://github.com/niiknow/vue-datatables-net/issues/21#issuecomment-572129857 and pass your Vue to the `vue` property instead of `jquery` property.

**Comment by joweste** [comment]
Thank but I think  the problem is the vue  version I have.  
I think I solve the jquery problem.
The problem now is: Runtime + Compiler vs. Runtime-only   of the Vue  package
I use https://github.com/vuejs-templates/webpack.
And I started my project with webpack selecting  Runtime Vue only when It asked me on init of the project. I dont´t know where is the config of webpack to change to full build version.
So, I am starting a new  project and I will select build version of the Vue

**Comment by joweste** [comment]
Thank you. It works as a charm.

**Comment by joweste** [comment]
Here is what I did:
import Vue from "vue";
import App from "./App";
import router from "./router";

import jQuery from "jquery";

import "bootstrap/dist/css/bootstrap.min.css";

window.Vue = Vue;
window.jQuery = jQuery;

Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  el: "#app",
  router,
  components: { App },
  template: "<App/>"
});

**Comment by joweste** [comment]
I had to choice Vue build version with webpack template

**Comment by joweste** [comment]
Why the ordering and search is not workink in https://niiknow.github.io/vue-datatables-net/  demo?

**Comment by noogen** [comment]
Because the server-side of that demo does not support sorting and search.   Use this for actual server-side demo: https://laratt.niiknow.org/home/contacts

**Comment by noogen** [comment]
Stale issue.
