### ISSUE TITLE
Intercept Ajax

### ISSUE THREAD

**Issue by ruelluna** [niiknow/vue-datatables-net#4]
Great wrapper! I switched to using this because of Laravel's data integration.

Just one thing though, I tried intercepting the ajax requests because I want to setup a fullscreen loading component and remove after successful draw.

What I tried so far is to use jQuery
```
  $.ajaxSetup({
        beforeSend: function (xhr,settings) {
            console.log('beforeSend')
        },
        ajaxComplete: function(xhr, settting){
            console.log('ajaxComplete')
        },
        ajaxError: function(){
            console.log('ajaxError')
        },
        ajaxStart: function(){
            console.log('ajaxStart')
        },
        ajaxStop: function(){
            console.log('ajaxStop')
        },
        ajaxSuccess: function(){
            console.log('ajaxSuccess')
        }

    });
```

Only the `beforeSend` event is being triggered. I will appreciate some guidance. Thank you for your wrapper!

**Comment by noogen** [comment]
@ruelluna I believe it's behaving correctly, as you have described, per documentation here: https://api.jquery.com/jquery.ajaxsetup/

To summarize `$.ajaxSetup` usage doc basically say that it is to setup `defaults` for `$.ajax` method.  No where in the settings document here https://api.jquery.com/jQuery.ajax/ that said it support those other functions.

If you go to the function documentation, example [`$ .ajaxComplete`](https://api.jquery.com/ajaxComplete/), it specifically identify itself as a global function that is wired up on the `document` object, per example on the documentation page.

Personally, I would not use global.  You can use `beforeSend` to intercept the before ajax and the table `reloaded` event ajax complete.  Alternatively, you can use the datatables.net native events [`preXhr`](https://datatables.net/reference/event/preXhr) and [`xhr.dt`](https://datatables.net/reference/event/xhr#Type) events.

**Comment by ruelluna** [comment]
Thanks!
