### ISSUE TITLE
Bug using plugin datatables.net-colreorder-bs4

### ISSUE THREAD

**Issue by juliorosseti** [niiknow/vue-datatables-net#40]
I realized that when trying to change the column positions the error below appears:
`Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.`

![image](https://user-images.githubusercontent.com/17995646/82492829-3a8c6f80-9abd-11ea-8097-2ce9c349bb3f.png)

I looked for the bug in the Datatables community and found this discussion:
https://datatables.net/forums/discussion/59248/colreorder-failed-to-execute-insertbefore-on-node-parameter-1-is-not-of-type-node

Then I realized that there are actually two "tr" in the code generated by the component:
![image](https://user-images.githubusercontent.com/17995646/82493010-9fe06080-9abd-11ea-8b9a-3b50b921c2a8.png)

When I remove the void "tr", the error no longer happens.

I used this code below in the function `@table-created="doCreated"`
```js
doCreated(comp) {
        this.$refs.table.$el
                .querySelector(".dataTables_scrollHead table thead tr")
                .remove()
}
```

BTW, thanks for developing this Vue wrapper component. Works great!

**Comment by noogen** [comment]
I notice the extra empty row in the thead too.  Seem to be bug in the base code when you define your own thead, which I feel iffy about patching within this component.  Since this component allow for defining your own thead, I will keep this issue open while I ponder more on if I should patch this.

**Comment by juliorosseti** [comment]
Your example just got a lot better, tks!

I did a test with the code above, but it only worked by changing "querySelector" to "querySelectorAll"

**Comment by vibonacci** [comment]
Quite annoying. I noticed it as well at some point using datatables.net iwthout this Vue wrapper. Of course should report to datatables.net author.

**Comment by noogen** [comment]
Stale issue.
