### ISSUE TITLE
Invalid prop: type check failed for prop "jquery" and "vue"

### ISSUE THREAD

**Issue by WinterMoring** [niiknow/vue-datatables-net#53]
I passed the jquery and vue into the component, and the table shows, but console shows Vue warn as 'Invalid prop: type check failed for prop "jquery". Expected Object, got Function' and 'Invalid prop: type check failed for prop "vue". Expected Object, got Function'.
How can I fix it?

**Comment by friedrichkeydel** [comment]
would be nice to get an answer for that!

**Comment by noogen** [comment]
Can you post example to show the error?  if possible use CDN ref https://unpkg.com/vue-datatables-net/dist/index.js so we can debug to see where the issue occurred.

**Comment by noogen** [comment]
See latest change to see if it is fixed.

**Comment by noogen** [comment]
Stale issue.
