### ISSUE TITLE
Dynamically Updating Cell?

### ISSUE THREAD

**Issue by simplyphp-kelly** [niiknow/vue-datatables-net#61]
Is it possible to have a cell that's constantly changing, like a countdown or a timer?  As far as I know, trying to use the render function won't work here, as it's only called on display and doesn't react to updates.

**Comment by noogen** [comment]
Same as issue #23 - it has to do with limitation of datatables.net - see issue #23 for possible resolution might only be able to resolve on datatables.net side.
