### ISSUE TITLE
saveState not working

### ISSUE THREAD

**Issue by sejanH** [niiknow/vue-datatables-net#64]
I tried by setting the id.
![image](https://user-images.githubusercontent.com/16546092/125208224-17b9ad80-e2b3-11eb-92bc-d69a2cb19729.png)
Also opts object got the saveState: true

**Comment by noogen** [comment]
Save state is all handled by jQuery datatables.net, see documentation here:  https://datatables.net/reference/option/stateSave

I'm not doing anything special.  Make sure table has an id and unique combine with the URL.

**Comment by sejanH** [comment]
> Save state is all handled by jQuery datatables.net, see documentation here: https://datatables.net/reference/option/stateSave
> 
> I'm not doing anything special. Make sure table has an id and unique combine with the URL.

I am doing everything mentioned. but can't get it to work

**Comment by noogen** [comment]
So we all seem to have `Dyslexia` issue.  The actual property is `saveState` and **not stateSave**

Code has been updated to 1.5.4 and demo is working in saving state.

**Comment by sejanH** [comment]
> So we all seem to have `Dyslexia` issue. The actual property is `stateSave` and **not saveState**
> 
> Code has been updated to 1.5.4 and demo is working in saving state. https://niiknow.github.io/vue-datatables-net/

Yeah in the it's still ```saveState``` so I have been using that. using **stateSave** works
