### ISSUE TITLE
Send custom parameter and reload

### ISSUE THREAD

**Issue by yilmix** [niiknow/vue-datatables-net#65]
Hi

I want to use custom filter. 
I am using the code below, but when I call the reload method I cannot send this data

`<a @click="filterStatus()">Just Open</a>`

```
methods:{
            filterStatus(){
                this.$refs.table.opts.ajax.data={status:1};
                this.$refs.table.reload();
            },
        },
```
Is there any other way?

**Comment by noogen** [comment]
See issue #63 on how to send custom parameters.   Put it beforeSend on opts.ajax like shown here: https://github.com/niiknow/vue-datatables-net#additional-headers

**Comment by noogen** [comment]
Stale issue.
