### ISSUE TITLE
Integrate with laravel datatable

### ISSUE THREAD

**Issue by sakibwebworm** [niiknow/vue-datatables-net#8]
Hi , do you have any working example or do you know how it is possible to integrate it with Laravel datatables (yajira)

**Comment by noogen** [comment]
It's simple, just 3 lines of code as your controller method body:
```php
$query = YourModel::query();
$dt       = DataTables::of($query);
return $dt->make(true);
```

Demo: http://laratt.niiknow.org/home/contacts
Src: https://github.com/niiknow/laratt-api/blob/master/api/Controllers/DemoContactController.php#L68

Demo has extra code to support/demonstrate exporting.

**Comment by noogen** [comment]
Old issue with no updates.
